spring:
  profiles:
    active: dev-h2

---

spring:
  profiles: dev-h2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  livereload:
    enabled: true
  thymeleaf:
    cache: false

dialect: MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---

spring:
  profiles: dev-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/omgg?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  livereload:
    enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace